# ============================================================
# Install Reverse SSH Tunnel as Windows Scheduled Task
# (Auto-start on boot + Auto-reconnect)
# Run PowerShell as Administrator
# ============================================================

param(
    [string]$VPS_IP = "",
    [string]$VPS_USER = "tunnel",
    [string]$VPS_SSH_PORT = "",
    [int]$REMOTE_PORT = 0,
    [int]$LOCAL_PORT = 22
)

$TaskName = "ReverseSSHTunnel"
$KeyPath = Join-Path $env:USERPROFILE ".ssh\id_ed25519_tunnel"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$WrapperScript = Join-Path $ScriptDir "tunnel-keepalive.ps1"
$ConfigFile = Join-Path $ScriptDir "vps-config.json"

# ---------- 0. Check Administrator Privileges ----------
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
if (-not $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Host "ERROR: Please run this script as Administrator!" -ForegroundColor Red
    Write-Host "Right-click PowerShell and select 'Run as Administrator'." -ForegroundColor White
    exit 1
}

if (Test-Path $ConfigFile) {
    $saved = Get-Content $ConfigFile -Raw | ConvertFrom-Json
    if (-not $VPS_IP -and $saved.VPS_IP) { $VPS_IP = $saved.VPS_IP }
    if (-not $VPS_SSH_PORT -and $saved.VPS_SSH_PORT) { $VPS_SSH_PORT = [string]$saved.VPS_SSH_PORT }
    if ($REMOTE_PORT -eq 0 -and $saved.PC_PORTS) {
        $myPort = $saved.PC_PORTS.($env:COMPUTERNAME)
        if ($myPort) { $REMOTE_PORT = [int]$myPort }
    }
}
if ($REMOTE_PORT -eq 0) { $REMOTE_PORT = 2222 }
if (-not $VPS_IP) {
    Write-Host "ERROR: VPS_IP not found. Run sync-to-vps.ps1 first or pass -VPS_IP." -ForegroundColor Red
    exit 1
}
if (-not $VPS_SSH_PORT) { $VPS_SSH_PORT = "22" }
$VPS_SSH_PORT = [int]$VPS_SSH_PORT

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host " Install Reverse Tunnel Service" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan

# ---------- 1. Generate keepalive script ----------
Write-Host ""
Write-Host "[1/3] Generating keepalive script..." -ForegroundColor Yellow

$sshTargetStr = $VPS_USER + '@' + $VPS_IP
$keepAliveLines = @()
$keepAliveLines += '# Reverse SSH Tunnel Keepalive Script'
$keepAliveLines += '# Auto-generated by install-tunnel-service.ps1'
$keepAliveLines += ''
$keepAliveLines += '$VPS_IP = "' + $VPS_IP + '"'
$keepAliveLines += '$VPS_USER = "' + $VPS_USER + '"'
$keepAliveLines += '$VPS_SSH_PORT = ' + $VPS_SSH_PORT
$keepAliveLines += '$REMOTE_PORT = ' + $REMOTE_PORT
$keepAliveLines += '$LOCAL_PORT = ' + $LOCAL_PORT
$keepAliveLines += '$KeyPath = "' + $KeyPath + '"'
$keepAliveLines += '$LogFile = "' + $ScriptDir + '\tunnel.log"'
$keepAliveLines += ''
$keepAliveLines += 'function Write-Log {'
$keepAliveLines += '    param([string]$Message)'
$keepAliveLines += '    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"'
$keepAliveLines += '    "$timestamp - $Message" | Out-File -Append -FilePath $LogFile -Encoding UTF8'
$keepAliveLines += '}'
$keepAliveLines += ''
$keepAliveLines += 'Write-Log "Keepalive script started"'
$keepAliveLines += ''
$keepAliveLines += 'while ($true) {'
$keepAliveLines += '    $existingProcess = Get-Process -Name "ssh" -ErrorAction SilentlyContinue'
$keepAliveLines += ''
$keepAliveLines += '    if (-not $existingProcess) {'
$keepAliveLines += '        Write-Log "Starting reverse SSH tunnel..."'
$keepAliveLines += '        $sshTarget = $VPS_USER + ''@'' + $VPS_IP'
$keepAliveLines += '        $sshArgs = @('
$keepAliveLines += '            "-i", $KeyPath,'
$keepAliveLines += '            "-N",'
$keepAliveLines += '            "-o", "ExitOnForwardFailure=yes",'
$keepAliveLines += '            "-o", "ServerAliveInterval=30",'
$keepAliveLines += '            "-o", "ServerAliveCountMax=3",'
$keepAliveLines += '            "-o", "StrictHostKeyChecking=accept-new",'
$keepAliveLines += '            "-o", "TCPKeepAlive=yes",'
$keepAliveLines += '            "-R", ($REMOTE_PORT.ToString() + ":localhost:" + $LOCAL_PORT.ToString()),'
$keepAliveLines += '            "-p", $VPS_SSH_PORT,'
$keepAliveLines += '            $sshTarget'
$keepAliveLines += '        )'
$keepAliveLines += '        try {'
$keepAliveLines += '            Start-Process -FilePath "ssh" -ArgumentList $sshArgs -NoNewWindow -Wait'
$keepAliveLines += '            Write-Log "SSH tunnel exited. Reconnecting in 10s..."'
$keepAliveLines += '        } catch {'
$keepAliveLines += '            Write-Log ("SSH tunnel failed: " + $_.Exception.Message)'
$keepAliveLines += '        }'
$keepAliveLines += '    } else {'
$keepAliveLines += '        Write-Log ("SSH tunnel running (PID: " + $existingProcess.Id + ")")'
$keepAliveLines += '    }'
$keepAliveLines += ''
$keepAliveLines += '    Start-Sleep -Seconds 10'
$keepAliveLines += '}'

$keepAliveContent = $keepAliveLines -join "`r`n"
Set-Content -Path $WrapperScript -Value $keepAliveContent -Encoding UTF8
Write-Host ("  Keepalive script: " + $WrapperScript) -ForegroundColor Green

# ---------- 2. Create scheduled task ----------
Write-Host ""
Write-Host "[2/3] Creating scheduled task..." -ForegroundColor Yellow

$existingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existingTask) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "  Removed old task."
}

$trigger = New-ScheduledTaskTrigger -AtLogOn

$actionArg = "-ExecutionPolicy Bypass -WindowStyle Hidden -File """ + $WrapperScript + """"
$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $actionArg

$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -ExecutionTimeLimit (New-TimeSpan -Days 365)

$taskDesc = "Reverse SSH Tunnel - auto connect to VPS (" + $VPS_IP + ")"
Register-ScheduledTask -TaskName $TaskName -Trigger $trigger -Action $action -Settings $settings -Description $taskDesc -RunLevel Highest

Write-Host ("  Task created: " + $TaskName) -ForegroundColor Green

# ---------- 3. Start now ----------
Write-Host ""
Write-Host "[3/3] Starting tunnel..." -ForegroundColor Yellow
Start-ScheduledTask -TaskName $TaskName

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host " Tunnel Service Installed!" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host ("  Task Name  : " + $TaskName) -ForegroundColor White
Write-Host ("  Keepalive  : " + $WrapperScript) -ForegroundColor White
Write-Host ("  Log File   : " + $ScriptDir + "\tunnel.log") -ForegroundColor White
Write-Host ""
Write-Host "Management commands:" -ForegroundColor Yellow
Write-Host ("  Get-ScheduledTask -TaskName " + $TaskName) -ForegroundColor White
Write-Host ("  Start-ScheduledTask -TaskName " + $TaskName) -ForegroundColor White
Write-Host ("  Stop-ScheduledTask -TaskName " + $TaskName) -ForegroundColor White
Write-Host ("  Unregister-ScheduledTask -TaskName " + $TaskName) -ForegroundColor White
Write-Host "  Get-Process ssh | Stop-Process -Force" -ForegroundColor White
Write-Host ""
